//
// Created by Lukas Bos on 30/12/2019.
//

#ifndef RTT_ROBOTEAM_MONITOR_SRC_UTILS_THEME_H_
#define RTT_ROBOTEAM_MONITOR_SRC_UTILS_THEME_H_

class theme {

};

#endif //RTT_ROBOTEAM_MONITOR_SRC_UTILS_THEME_H_
